# Generated by Django 5.2.8 on 2025-11-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('probability_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('ambiance', models.CharField(max_length=100)),
                ('keywords', models.TextField(blank=True)),
                ('prompt_background', models.TextField(blank=True)),
                ('integration_idea', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('keywords', models.TextField(blank=True)),
                ('composition_hint', models.TextField(blank=True)),
                ('rarety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='style.rarity')),
            ],
        ),
    ]
