# Generated by Django 5.2.8 on 2025-11-16 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rarity',
            options={'verbose_name_plural': 'Rarities'},
        ),
        migrations.RemoveField(
            model_name='rarity',
            name='probability_weight',
        ),
        migrations.RemoveField(
            model_name='style',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='style',
            name='rarety',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='keywords',
        ),
        migrations.AddField(
            model_name='rarity',
            name='min_roll_threshold',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rarity',
            name='ui_color_hex',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='style',
            name='rarity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='style.rarity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='style',
            name='style_keywords',
            field=models.TextField(blank=True, help_text="Prompts pour l'IA (ex: chibi style, cute, simple)"),
        ),
        migrations.AddField(
            model_name='theme',
            name='keywords_theme',
            field=models.TextField(blank=True, help_text="Prompts pour l'IA (ex: moniteurs multiples, lignes de code)"),
        ),
        migrations.AlterField(
            model_name='rarity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='composition_hint',
            field=models.TextField(blank=True, help_text="Rappel sur comment l'utiliser"),
        ),
        migrations.AlterField(
            model_name='theme',
            name='ambiance',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='theme',
            name='category',
            field=models.CharField(blank=True, help_text='Ex: Technologie, Fitness, Fantaisie', max_length=100),
        ),
        migrations.AlterField(
            model_name='theme',
            name='integration_idea',
            field=models.TextField(blank=True, help_text='Rappel sur comment intégrer le personnage'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='prompt_background',
            field=models.TextField(blank=True, help_text="Le prompt de fond complet pour l'IA"),
        ),
    ]
