# Generated by Django 5.2.8 on 2025-11-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0003_populate_gacha_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='unlock_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='theme',
            name='unlock_level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
