# Generated by Django 5.2.8 on 2025-12-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0004_style_unlock_level_theme_unlock_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='base_rarity_tier',
            field=models.PositiveIntegerField(default=1, help_text='1=Basic, 5=Legendary'),
        ),
        migrations.AddField(
            model_name='theme',
            name='vibe_tags',
            field=models.JSONField(blank=True, default=list, help_text="Mots-clés de l'ambiance (ex: ['sacred', 'colorful light'])"),
        ),
    ]
