# Generated by Django 5.2.8 on 2025-11-20 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0002_series_description'),
        ('style', '0003_populate_gacha_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('currency_reward', models.PositiveIntegerField(default=10)),
                ('type', models.CharField(choices=[('DAILY', 'Daily'), ('ACHIEVEMENT', 'Achievement')], default='DAILY', max_length=20)),
                ('condition_key', models.CharField(help_text="Key to identify the condition in code (e.g., 'task_completed')", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.charactervariant')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='style.rarity')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='style.style')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='style.theme')),
            ],
            options={
                'unique_together': {('character_variant', 'rarity', 'style', 'theme')},
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('gatcha_coins', models.PositiveIntegerField(default=0)),
                ('ticktick_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('claimed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='gamification.player')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.quest')),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='gamification.player')),
            ],
            options={
                'unique_together': {('player', 'card')},
            },
        ),
    ]
