# Generated by Django 5.2.8 on 2025-12-06 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_player_current_streak_player_last_activity_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCompanionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('character_name', models.CharField(max_length=100)),
                ('mood_state', models.CharField(choices=[('SAD', 'Sad'), ('NEUTRAL', 'Neutral'), ('HAPPY', 'Happy'), ('EXCITED', 'Excited')], default='NEUTRAL', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='companion_daily/')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('dialogue_text', models.TextField(blank=True)),
                ('productivity_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_states', to='gamification.player')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('player', 'date')},
            },
        ),
    ]
