# Generated by Django 5.2.8 on 2025-12-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_player_current_streak_player_last_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='legacy',
            field=models.BooleanField(default=False),
        ),
    ]
