# Generated by Django 5.2.8 on 2026-01-03 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_card_legacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTamagotchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mood', models.FloatField(default=100.0)),
                ('satiety', models.FloatField(default=100.0)),
                ('last_decay_update', models.DateTimeField(auto_now_add=True)),
                ('sleep_start_hour', models.IntegerField(default=23)),
                ('sleep_end_hour', models.IntegerField(default=7)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_tamagotchi', to='gamification.player')),
            ],
        ),
    ]
