# Generated by Django 5.2.8 on 2026-01-03 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_charactervariant_legacy'),
        ('gamification', '0004_activetamagotchi'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetamagotchi',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='character.character'),
        ),
        migrations.AlterField(
            model_name='activetamagotchi',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
