# Generated by Django 5.2.8 on 2026-01-03 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_charactervariant_legacy'),
        ('gamification', '0005_activetamagotchi_character_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='companion_images/')),
                ('min_mood', models.FloatField(default=0.0)),
                ('max_mood', models.FloatField(default=100.0)),
                ('is_sleep_state', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_images', to='character.character')),
            ],
        ),
    ]
