# Generated by Django 5.2.8 on 2026-01-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_companionimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companionimage',
            name='is_sleep_state',
        ),
        migrations.RemoveField(
            model_name='companionimage',
            name='max_mood',
        ),
        migrations.RemoveField(
            model_name='companionimage',
            name='min_mood',
        ),
        migrations.AddField(
            model_name='companionimage',
            name='state',
            field=models.CharField(choices=[('EXTREMELY_HAPPY', 'Extremely Happy (80-100%)'), ('HAPPY', 'Happy (60-80%)'), ('NEUTRAL', 'Neutral (40-60%)'), ('POUTING', 'Pouting (20-40%)'), ('DISTRESSED', 'Very Distressed (1-20%)'), ('DEAD', 'Dead (0%)'), ('SLEEPING', 'Sleeping')], default='NEUTRAL', max_length=20),
        ),
    ]
