# Generated by Django 5.2.8 on 2026-01-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_charactervariant_legacy'),
        ('gamification', '0007_remove_companionimage_is_sleep_state_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companionimage',
            unique_together={('character', 'state')},
        ),
    ]
