# Generated by Django 5.2.8 on 2026-01-04 21:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0008_alter_companionimage_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activetamagotchi',
            name='satiety',
        ),
        migrations.AddField(
            model_name='activetamagotchi',
            name='feeds_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activetamagotchi',
            name='last_daily_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activetamagotchi',
            name='pets_today',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
