# Generated by Django 5.2.8 on 2026-01-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0009_remove_activetamagotchi_satiety_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activetamagotchi',
            name='feeds_today',
        ),
        migrations.RemoveField(
            model_name='activetamagotchi',
            name='pets_today',
        ),
        migrations.AddField(
            model_name='activetamagotchi',
            name='last_feed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activetamagotchi',
            name='last_pet_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
