# Generated by Django 5.2.8 on 2025-11-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_series_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='unlock_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='series',
            name='unlock_level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
