# Generated by Django 5.2.8 on 2025-12-10 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_character_unlock_level_series_unlock_level'),
        ('style', '0005_theme_base_rarity_tier_theme_vibe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='affinity_environments',
            field=models.JSONField(blank=True, default=list, help_text="ex: ['shadows', 'city night']"),
        ),
        migrations.AddField(
            model_name='character',
            name='body_type_description',
            field=models.CharField(blank=True, help_text='ex: petite stature, slender build, flat chest', max_length=255),
        ),
        migrations.AddField(
            model_name='character',
            name='clashing_environments',
            field=models.JSONField(blank=True, default=list, help_text="ex: ['holy church', 'bright beach']"),
        ),
        migrations.AddField(
            model_name='character',
            name='height_perception',
            field=models.CharField(blank=True, help_text='ex: short, tall, giant', max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='identity_face_image',
            field=models.ImageField(blank=True, null=True, upload_to='character_faces/'),
        ),
        migrations.AddField(
            model_name='character',
            name='lore_tags',
            field=models.JSONField(blank=True, default=list, help_text="ex: ['stealth', 'modern', 'cynical']"),
        ),
        migrations.AddField(
            model_name='charactervariant',
            name='specific_reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='variant_refs/'),
        ),
        migrations.AddField(
            model_name='charactervariant',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='style.theme'),
        ),
        migrations.AddField(
            model_name='charactervariant',
            name='variant_type',
            field=models.CharField(choices=[('CANON', 'Canon'), ('SKIN', 'Skin')], default='CANON', max_length=10),
        ),
        migrations.AddField(
            model_name='charactervariant',
            name='visual_override',
            field=models.TextField(blank=True, help_text="Description de la tenue et de l'adaptation"),
        ),
    ]
