# Generated by Django 5.2.8 on 2025-12-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_character_affinity_environments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='eye_prompt',
            field=models.TextField(blank=True, help_text='Description visuelle des yeux'),
        ),
        migrations.AddField(
            model_name='character',
            name='hair_prompt',
            field=models.TextField(blank=True, help_text='Description visuelle des cheveux'),
        ),
        migrations.AddField(
            model_name='character',
            name='negative_traits_suggestion',
            field=models.TextField(blank=True, help_text='Negative prompt morphologique'),
        ),
        migrations.AddField(
            model_name='character',
            name='visual_traits',
            field=models.JSONField(blank=True, default=list, help_text="Liste de traits physiques immuables ex: ['scar on left eye', 'pale skin']"),
        ),
        migrations.AlterField(
            model_name='character',
            name='affinity_environments',
            field=models.JSONField(blank=True, default=list, help_text="ex: [{'name': 'shadows', 'visual_prompt': 'dark alley'}]"),
        ),
        migrations.AlterField(
            model_name='character',
            name='height_perception',
            field=models.CharField(blank=True, choices=[('SHORT', 'Short'), ('AVERAGE', 'Average'), ('TALL', 'Tall'), ('GIANT', 'Giant')], default='AVERAGE', help_text='ex: short, tall, giant', max_length=50),
        ),
    ]
