# Generated by Django 5.2.8 on 2025-12-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0005_character_eye_prompt_character_hair_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactervariant',
            name='compatible_themes_data',
            field=models.JSONField(blank=True, default=list, help_text='AI generated compatible themes for this variant'),
        ),
    ]
