# Generated by Django 5.2.8 on 2025-12-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_charactervariant_compatible_themes_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='legacy',
            field=models.BooleanField(default=False),
        ),
    ]
