# Generated by Django 5.2.8 on 2025-12-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_character_legacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactervariant',
            name='compatible_themes_data',
        ),
        migrations.AddField(
            model_name='charactervariant',
            name='card_configurations_data',
            field=models.JSONField(blank=True, default=list, help_text='AI generated card configurations (rarity, pose, theme, style)'),
        ),
    ]
