# Generated by Django 5.2.8 on 2025-12-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_remove_charactervariant_compatible_themes_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactervariant',
            name='variant_type',
            field=models.CharField(choices=[('CANON', 'Canon'), ('SKIN', 'Skin')], default='CANON', max_length=50),
        ),
    ]
