# Generated by Django 5.2.8 on 2025-12-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_alter_charactervariant_variant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactervariant',
            name='legacy',
            field=models.BooleanField(default=False),
        ),
    ]
