# Generated by Django 5.2.8 on 2025-11-15 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_series_description'),
        ('generated_image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='character_variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='character.charactervariant'),
            preserve_default=False,
        ),
    ]
