# Generated by Django 5.2.8 on 2025-11-16 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generated_image', '0002_generatedimage_character_variant'),
        ('style', '0003_populate_gacha_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='rarity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='style.rarity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='style.style'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='style.theme'),
            preserve_default=False,
        ),
    ]
