# Generated by Django 5.2.8 on 2025-12-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generated_image', '0003_generatedimage_rarity_generatedimage_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='generated_images/thumbnails/'),
        ),
    ]
