# Generated by Django 5.2.8 on 2025-11-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TickTickColumn',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('projectId', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('sortOrder', models.BigIntegerField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'columns',
            },
        ),
        migrations.CreateModel(
            name='TickTickProject',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('sortOrder', models.BigIntegerField(blank=True, null=True)),
                ('groupid', models.CharField(blank=True, max_length=255, null=True)),
                ('viewmode', models.CharField(blank=True, max_length=50, null=True)),
                ('kind', models.CharField(blank=True, max_length=50, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='TickTickTask',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('projectId', models.CharField(blank=True, max_length=255, null=True)),
                ('columnId', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=1024)),
                ('content', models.TextField(blank=True, null=True)),
                ('task_desc', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('sortOrder', models.BigIntegerField(blank=True, null=True)),
                ('kind', models.CharField(blank=True, max_length=50, null=True)),
                ('reminders', models.JSONField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('parentId', models.CharField(blank=True, max_length=255, null=True)),
                ('isAllDay', models.BooleanField(default=False)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('timeZone', models.CharField(blank=True, max_length=100, null=True)),
                ('repeatFlag', models.CharField(blank=True, max_length=100, null=True)),
                ('etag', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
