# Generated by Django 5.2.8 on 2025-11-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticktick', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticktickcolumn',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ticktickproject',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tickticktask',
            options={'managed': False},
        ),
    ]
