# Generated by Django 5.2.8 on 2025-11-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticktick', '0002_alter_ticktickcolumn_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedtask',
            name='task_title',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
