# Generated by Django 5.2.8 on 2025-12-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticktick', '0003_processedtask_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedtask',
            name='base_reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processedtask',
            name='coin_gain',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processedtask',
            name='crit_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='processedtask',
            name='daily_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processedtask',
            name='difficulty',
            field=models.CharField(default='easy', max_length=50),
        ),
        migrations.AddField(
            model_name='processedtask',
            name='is_crit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processedtask',
            name='streak_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='processedtask',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedtask',
            name='xp_gain',
            field=models.IntegerField(default=0),
        ),
    ]
